# Generated by Django 2.0.2 on 2018-06-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('address', models.CharField(max_length=32, verbose_name='адрес')),
                ('author', models.CharField(blank=True, max_length=32, verbose_name='автор')),
                ('publishing', models.CharField(blank=True, max_length=32, verbose_name='издательство')),
                ('papers', models.CharField(blank=True, max_length=32, verbose_name='количество и тип страниц')),
                ('mass', models.IntegerField(default=0, verbose_name='масса')),
                ('size', models.CharField(blank=True, max_length=32, verbose_name='размер')),
                ('disc', models.TextField(blank=True, verbose_name='кратко')),
                ('extra_disc', models.TextField(blank=True, verbose_name='подробно')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='категория')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.BookCategory'),
        ),
    ]
